CREATE TABLE IF NOT EXISTS tokens (
	id SERIAL PRIMARY KEY,
	token VARCHAR(16) UNIQUE NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

